//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerP360Insight.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMensajesP360 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensajesP360() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulerP360Insight.Properties.ResourceMensajesP360", typeof(ResourceMensajesP360).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un error en la ejecución de la consulta, verifique que haya seleccionado los parámetros adecuados..
        /// </summary>
        internal static string mensaje_errorSQL_102 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave o usuario de DataWarehouse Central P360° incorrecto. Solicite soporte al administrador técnico de la plataforma..
        /// </summary>
        internal static string mensaje_errorSQL_18456 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información que está ingresando está ya registrada o duplicada. Verifíquela y realice la respectiva validación y ajustes necesarios..
        /// </summary>
        internal static string mensaje_errorSQL_2627 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer la conexión a la Base de Datos central de la Plataforma de Inteligencia de Negocios P360°. Usted podría estar desconectado de la red o el DataWarehouse podría estar indisponible..
        /// </summary>
        internal static string mensaje_errorSQL_4060 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de uno de los campos cargados es muy extensa..
        /// </summary>
        internal static string mensaje_errorSQL_4815 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_4815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información que está ingresando está en blanco. Verifíquela y realice la respectiva validación y ajustes necesarios..
        /// </summary>
        internal static string mensaje_errorSQL_515 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer la conexión a la Base de Datos central de la Plataforma de Inteligencia de Negocios P360°. Usted podría estar desconectado de la red o el DataWarehouse podría estar indisponible..
        /// </summary>
        internal static string mensaje_errorSQL_53 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información que esta procesando contiene errores. Valide que los campos numéricos tengan el formato adecuado..
        /// </summary>
        internal static string mensaje_errorSQL_8114 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_8114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error aritmético de división por cero en alguno de los cálculos del reporte. Por favor repórtelo al administrador del sistema..
        /// </summary>
        internal static string mensaje_errorSQL_8134 {
            get {
                return ResourceManager.GetString("mensaje_errorSQL_8134", resourceCulture);
            }
        }
    }
}
