//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerP360Insight.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePlantillasEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePlantillasEmail() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulerP360Insight.Properties.ResourcePlantillasEmail", typeof(ResourcePlantillasEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///        &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            background- [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_01 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            background-colo [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_02 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///        &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            background- [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_03 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_04 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_05 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_06 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_07 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_08 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_09 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_10 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_11 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///    &lt;meta name=&quot;GENERATOR&quot; content=&quot;Pharma360°&quot;&gt;
        ///            &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            background-color: #f4f4f4;
        ///        }
        ///
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 5px;
        ///            backgro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTMLBody_Plantilla_VM_12 {
            get {
                return ResourceManager.GetString("HTMLBody_Plantilla_VM_12", resourceCulture);
            }
        }
    }
}
